accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [ #wiazanie widoku z django z templatka login.html
    path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'), #idzie do homepage
    path('signup/', views.register, name='signup'),
    path('after_signup/', views.AfterRegisterPage.as_view(), name="after_signup"),

    path('password_reset/',  
            auth_views.PasswordResetView.as_view(template_name="accounts/password_reset_form.html"), 
            name='password_reset'
        ),

    path('password_reset/done/',
            auth_views.PasswordResetDoneView.as_view(template_name= "accounts/password_reset_done.html"), 
            name='password_reset_done'
        ),
    
    path('accounts/reset_password_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='reset_password_confirm'),

    path('reset/done/',
            auth_views.PasswordResetCompleteView.as_view(template_name= "accounts/password_reset_complete.html"), 
            name='password_reset_complete'
        ),

    path('my_profile/', views.MyProfileTemplateView.as_view(), name='my_profile'),
    path('my_profile_update/<int:pk>/', views.UpdateMyProfileView.as_view(), name='my_profile_update'),


    path('users_list/', views.UsersListView.as_view(), name='users_list'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('user_grant/<int:pk>/', views.UserGrantDetailView.as_view(), name='user_grant'),
    path('user_activate/<int:pk>/', views.UserActivateDetailView.as_view(), name='user_activate'),
    path('user_deactivate/<int:pk>/', views.UserDeactivateDetailView.as_view(), name='user_deactivate'),
    path('get_rights/<int:pk>/', views.UserGetRightsDetailView.as_view(), name='get_rights'),
]  

ems_app/urls.py
from django.urls import path

from ems_app import views

app_name = 'ems_app'

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
]

ems_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from ems_app.views import NoPermsPage
from accounts.views import UserAutocomplete, UserAdminsAutocomplete
from django_private_chat import urls as django_private_chat_urls



urlpatterns = [
    path('', include('ems_app.urls')),
    path('projects/', include('project_app.urls')),
    path('holiday/', include('holiday_app.urls')),
    path('resources/', include('resources_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('msg/', include('django_private_chat.urls')),
    path('no-permission/', NoPermsPage.as_view(), name="no_permission"),
    path('user-autocomplete/', UserAutocomplete.as_view(),name='user_autocomplete'),
    path('user-admin-autocomplete/', UserAdminsAutocomplete.as_view(),name='user_admin_autocomplete'),
] 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


# Create your models here.

#create your own user class.
class MyUser(AbstractUser):
    def __init__(self, *args, **kwargs):
        self._meta.get_field('email').blank = False
        self._meta.get_field('email')._unique = True
        super(MyUser, self).__init__(*args, **kwargs)

    class Meta:
       app_label = 'accounts'

    def __str__(self):
        return "ID: " + str(self.id) +  " " + self.get_full_name() 

class UserStateModel(models.Model):
    state_description = models.CharField(max_length=50, verbose_name='Stan użytkownika')

    def __str__(self):
            return self.state_description

class WorkHoursModel(models.Model):
    description = models.CharField(max_length=200, verbose_name='Opis zmiany')
    rate_of_pay = models.DecimalField(verbose_name='Stawka płacy', default=1.00, max_digits=3, decimal_places=2)

    def __str__(self):
            return self.description

class UserProfileInfo(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE, verbose_name='Użytkownik', related_name='user_profile')
    user_manager = models.ForeignKey(MyUser, on_delete=models.DO_NOTHING, null=True, blank=True, verbose_name='Kierownik', related_name='user_manager')
    user_work_hours = models.ForeignKey(WorkHoursModel, null=True, blank=False, on_delete=models.DO_NOTHING, verbose_name='Godziny pracy', related_name='user_work_hours')
    user_state = models.ForeignKey(UserStateModel, null=True, blank=False, on_delete=models.DO_NOTHING, verbose_name='Stan użytkownika', related_name='user_state')
    pesel = models.CharField(max_length=11, verbose_name='PESEL')
    street = models.CharField(max_length=200, verbose_name='Ulica')
    city = models.CharField(max_length=200, verbose_name='Miasto')
    phone = models.CharField(max_length=20, verbose_name='Telefon')
    post_code = models.CharField(max_length=6, verbose_name='Kod pocztowy')
    house_number = models.CharField(max_length=20, verbose_name='Numer domu')
    image = models.ImageField(upload_to='avatars/', default=None, null=True, blank=True)

    def __str__(self):
        return str(self.user.id) +', ' + self.user.get_full_name() + ',  PESEL: ' + self.pesel

class UserAccessModel(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.DO_NOTHING, verbose_name='Użytkownik', related_name='user_access')
    rfid = models.CharField(max_length=200, verbose_name='rfid')
    comments = models.CharField(max_length=500, verbose_name='uwagi', null=True, blank=True)

    def __str__(self):
            return self.user.get_full_name() + ',  PESEL: ' + self.pesel

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms
from accounts import models


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2')
        model = get_user_model()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserProfileInfo
        fields = ('user_manager', 'user_work_hours', 'user_state', 'phone', 'pesel', 'street',
                  'house_number', 'city', 'post_code', 'image')
        labels = {
            'user_manager': 'Kierownik',
            'user_work_hours': 'Godziny pracy',
            'user_state': 'Status pracownika',
            'phone': 'Telefon',
            'pesel': 'PESEL',
            'street': 'Ulica',
            'house_number': 'Numer domu',
            'city': 'Miasto',
            'post_code': 'Kod pocztowy',
            'image': 'Zdjęcie'
        }

    def __init__(self, **kwargs):
        super(ProfileForm, self).__init__(**kwargs)
        self.fields['user_manager'].queryset = models.MyUser.objects.filter(is_superuser=True)



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = models.UserProfileInfo
        fields = ('phone', 'pesel', 'street',
                  'house_number', 'city', 'post_code', 'image')
        labels = {
            'phone': 'Telefon',
            'pesel': 'PESEL',
            'street': 'Ulica',
            'house_number': 'Numer domu',
            'city': 'Miasto',
            'post_code': 'Kod pocztowy',
            'image': 'Zdjęcie'
        }

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, DetailView, UpdateView, ListView
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin
from dal import autocomplete

from accounts import models
from accounts import forms

from django.contrib.auth.decorators import login_required



# Create your views here.
@login_required
def register(request):

    registered = False

    if request.method == "POST":
        user_form = forms.UserCreateForm(data=request.POST)
        profile_form = forms.ProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.is_active = True
            user.save()
            

            profile = profile_form.save(commit=False)
            # w modelu profile jest pole user z relacja 1do1 wiec uzupelniamy je
            profile.user = user
            profile.image = request.FILES['image'] #dołączenie zdjęcia do profiluvisual
            profile.save()

            registered = True
            return redirect('accounts:after_signup')
        else:
            print(user_form.errors, profile_form.errors)

    else:  # jesli nie przeslemy nic w formularzu
        user_form = forms.UserCreateForm()
        profile_form = forms.ProfileForm()

    return render(request, 'accounts/signup.html',
                  context={'register_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})

class AfterRegisterPage(TemplateView):
    template_name = "accounts/after_signup.html"


class MyProfileTemplateView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'accounts/my_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_profile"] = models.UserProfileInfo.objects.get(user=self.request.user)
        return context





#### MANGE USERS VIEWS
class UsersListView(LoginRequiredMixin, SuperuserRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:login')
    model = models.UserProfileInfo
    paginate_by = 10
    context_object_name = "users_profiles_list"
    template_name = 'manage_accounts/users_list.html'

    def get_queryset(self):
        search_query = self.request.GET.get("search_query")
        search_type = self.request.GET.get("search_type")
        if search_query is not None:
            if search_type == "full_name":
                return models.UserProfileInfo.objects.filter(user__first_name__icontains=search_query) | models.UserProfileInfo.objects.filter(user__last_name__icontains=search_query)
            elif search_type == "phone":
                authors_result = models.UserProfileInfo.objects.filter(phone__icontains=search_query)
                return authors_result
            elif search_type == "pesel":
                return models.UserProfileInfo.objects.filter(pesel__icontains=search_query)
        else:
            return models.UserProfileInfo.objects.all()

class UpdateMyProfileView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')

    model = models.UserProfileInfo
    template_name = 'accounts/my_profile_update_form.html'

    #zawsze wczytany zostanie tylko obiekt usera który jest zalogowany, nie moze on edytować innych userów
    def get_object(self):
        return self.request.user.user_profile

    def get_success_url(self):
            return reverse('accounts:my_profile')


    def get_form_class(self):
        if self.request.user.is_superuser:
            return forms.ProfileForm
        else:
            return forms.ProfileUpdateForm


class UserDetailView(LoginRequiredMixin, SuperuserRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = models.UserProfileInfo
    context_object_name = "user_profile"
    template_name = 'manage_accounts/user_detail.html'

class UserGrantDetailView(LoginRequiredMixin, SuperuserRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = models.UserProfileInfo
    context_object_name = "user_profile" 
    template_name = 'manage_accounts/user_grant.html'

    def post(self, request, pk):
        userProfileInfoObj = models.UserProfileInfo.objects.get(id=pk)
        userProfileInfoObj.user.is_superuser = True
        userProfileInfoObj.user.is_staff = True
        userProfileInfoObj.user.save() 
        return redirect('accounts:users_list')


class UserGetRightsDetailView(LoginRequiredMixin, SuperuserRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = models.UserProfileInfo
    context_object_name = "user_profile"
    template_name = 'manage_accounts/user_get_rights.html'

    def post(self, request, pk):
        userProfileInfoObj = models.UserProfileInfo.objects.get(id=pk)
        userProfileInfoObj.user.is_superuser = False
        userProfileInfoObj.user.is_staff = False
        userProfileInfoObj.user.save()  # zapisz usera
        return redirect('accounts:users_list')

class UserActivateDetailView(LoginRequiredMixin, SuperuserRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = models.UserProfileInfo
    context_object_name = "user_profile"
    template_name = 'manage_accounts/user_activate.html'

    def post(self, request, pk):
        userProfileInfoObj = models.UserProfileInfo.objects.get(id=pk)
        userProfileInfoObj.user.is_active = True
        userProfileInfoObj.user.save()  # zapisz usera
        return redirect('accounts:users_list')


class UserDeactivateDetailView(LoginRequiredMixin, SuperuserRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = models.UserProfileInfo
    context_object_name = "user_profile"
    template_name = 'manage_accounts/user_deactivate.html'

    def post(self, request, pk):
        userProfileInfoObj = models.UserProfileInfo.objects.get(id=pk)
        userProfileInfoObj.user.is_active = False
        userProfileInfoObj.user.save()  
        return redirect('accounts:users_list')


### AUTOCOMPLETE
class UserAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated:
            return models.MyUser.objects.none()

        qs = models.MyUser.objects.all()

        if self.q:
            qs = qs.filter(first_name__istartswith=self.q)

        return qs

class UserAdminsAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated:
            return models.MyUser.objects.none()

        qs = models.MyUser.objects.filter(is_superuser=True)

        if self.q:
            qs = qs.filter(first_name__istartswith=self.q)

        return qs

accounts/templates/manage_accounts/user_activate.html
{% extends "base.html" %}

{% block body_block %}

<div class="container text-center">
        <div class="page-title">
            <h3>Aktywować użytkownika?</h3>
        </div>

        <ul style="padding-left: 0">
                <li><b>Imię i nazwisko: </b>{{user_profile.user.get_full_name}}</li>
                <li><b>Email: </b> {{user_profile.user.email}}</li>
                <li><b>Telefon: </b>{{user_profile.phone}}</li>
                <li><b>PESEL: </b>{{user_profile.pesel}} </li>
                <li><b>Adres: </b>{{user_profile.street}}, {{user_profile.house_number}}, {{user_profile.post_code}} {{user_profile.city}} </li>
        </ul>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-success button" value="Aktywuj">

        </form>

        <div class="borrow_list_back_link button">
            <a href="{% url 'accounts:users_list' %}"><input type="button" class="btn btn-dark" value="Powrót"></a>
        </div>
</div>
{% endblock %}

accounts/templates/manage_accounts/user_deactivate.html
{% extends "base.html" %}

{% block body_block %}

<div class="container text-center">
        <div class="page-title">
            <h3>Dezaktywować użytkownika?</h3>
        </div>

        <ul style="padding-left: 0">
                <li><b>Imię i nazwisko: </b>{{user_profile.user.get_full_name}}</li>
                <li><b>Email: </b> {{user_profile.user.email}}</li>
                <li><b>Telefon: </b>{{user_profile.phone}}</li>
                <li><b>PESEL: </b>{{user_profile.pesel}} </li>
                <li><b>Adres: </b>{{user_profile.street}}, {{user_profile.house_number}}, {{user_profile.post_code}} {{user_profile.city}} </li>
        </ul>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger button" value="Dezaktywuj">
        </form>

        <div class="borrow_list_back_link button">
            <a href="{% url 'accounts:users_list' %}"><input type="button" class="btn btn-dark" value="Powrót"></a>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/manage_accounts/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block body_block %}



<div class="container text-center">
        <div class="page-title">
            <h3>Szczegóły użytkownika </h3>
        </div>

        <ul>
            <li><b>Imię i nazwisko: </b>{{user_profile.user.get_full_name}}</li>
            <li><b>Email: </b>{{user_profile.user.email}}</a></li>
            <li><b>Telefon: </b>{{user_profile.phone}}</li>
            <li><b>PESEL: </b>{{user_profile.pesel}} </li>
            <li><b>Adres: </b>{{user_profile.street}} {{user_profile.house_number}} {{user_profile.post_code}} {{user_profile.city}} </li>
            <br>

            <li><b>Typ konta: </b>
                {% if user_profile.user.is_superuser %}
                    Kierownik
                {% else %}
                    Pracownik
                {% endif %}
            </li>
            <li><b>Dołączył dnia: </b> {{user_profile.user.date_joined}}</li>
            <li><b>Ostatnie logowanie dnia: </b> {{user_profile.user.last_login}} </li>
            <li><b>Czy konto aktywne: </b>
                {% if user_profile.user.is_active %}
                    Tak
                {% else %}
                    Nie
                {% endif %}
            </li>
        </ul>
        <br>


        
        <!-- Aktywowanie usera -->
        {% if user.is_superuser and user_profile.user.is_active == False %}
            <div class="button">
                <a href="{% url 'accounts:user_activate' pk=user_profile.pk %}"><input type="submit" class="btn btn-success button" value="Aktywuj konto"></a>
            </div>
        {% endif %}
                            
        <!-- Dezaktywowanie usera -->
        {% if user_profile.user.is_active == True and user_obj_borrow.count == 0 and user_profile.user.is_superuser == False %}
            <div class="button">
                <a href="{% url 'accounts:user_deactivate' pk=user_profile.pk %}"><input type="submit" class="btn btn-danger button" value="Dezaktywuj konto"></a> 
            </div>
        {% endif %}

        <!-- Nadanie praw superusera -->
        {% if user_profile.user.is_active == True and user_profile.user.is_superuser == False %}
            <div class="button">
                <a href="{% url 'accounts:user_grant' pk=user_profile.pk %}"><input type="submit" class="btn btn-success" value="Nadaj uprawnienia"></a>
            </div>
        {% endif %}
                            
         <!-- Odebranie praw superusera -->
        {% if user.id is not user_profile.user.id and user_profile.user.is_active == True and user_profile.user.is_superuser == True %}
            <div class="button">
                <a href="{% url 'accounts:get_rights' pk=user_profile.pk %}"><input type="submit" class="btn btn-danger" value="Odbierz uprawnienia"></a>
            </div>
        {% endif %}
        
        <div class="borrow_list_back_link button">
            <a href="{% url 'accounts:users_list' %}"><input type="button" class="btn btn-dark" value="Powrót"></a>
        </div>

</div>
{% endblock %}

accounts/templates/manage_accounts/user_get_rights.html
{% extends "base.html" %}

{% block body_block %}

<div class="container">
        <div class="page-title">
        <h3>Odbierz uprawnienia</h3>

        <ul style="padding-left:0">
                <li><b>Imię i nazwisko: </b>{{user_profile.user.get_full_name}}</li>
                <li><b>Email: </b> {{user_profile.user.email}}</li>
                <li><b>Telefon: </b>{{user_profile.phone}}</li>
                <li><b>PESEL: </b>{{user_profile.pesel}} </li>
                <li><b>Adres: </b>{{user_profile.street}}, {{user_profile.house_number}}, {{user_profile.post_code}} {{user_profile.city}} </li>
        </ul>

        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger button" value="Odbierz prawa">
        </form>

        <div class="borrow_list_back_link button">
            <a href="{% url 'accounts:users_list' %}"><input type="button" class="btn btn-dark" value="Powrót"></a>
        </div>
        
    </div>
</div>
{% endblock %}

accounts/templates/manage_accounts/user_grant.html
{% extends "base.html" %}

{% block body_block %}

<div class="container text-center">
        <div class="page-title">
            <h3>Nadawanie uprawnień</h3>
        </div>
        
        <ul style="padding-left:0">
                <li><b>Imię i nazwisko: </b>{{user_profile.user.get_full_name}}</li>
                <li><b>Email: </b> {{user_profile.user.email}}</li>
                <li><b>Telefon: </b>{{user_profile.phone}}</li>
                <li><b>PESEL: </b>{{user_profile.pesel}} </li>
                <li><b>Adres: </b>{{user_profile.street}}, {{user_profile.house_number}}, {{user_profile.post_code}} {{user_profile.city}} </li>
        </ul>

        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-success button" value="Nadaj prawa">
        </form>

        <div class="borrow_list_back_link button">
            <a href="{% url 'accounts:users_list' %}"><input type="button" class="btn btn-dark" value="Powrót"></a>
        </div>

    </div>
</div>
{% endblock %}

accounts/templates/manage_accounts/users_list.html
{% extends "base.html" %}
{% load static %}



{% block body_block %}
<div class="container">
    <div class="page-title">
        <h2>Zarządzaj użytkownikami</h2>
    </div>


<div class="search-bar">
<form class="form-inline" action="{% url 'accounts:users_list' %}" method="GET">
    <div class="input-group">
        <input type="search" class="form-control" name="search_query" placeholder="Wyszukaj">
        <select class="search-select" name="search_type">
            <option value="full_name" selected>Imie i/lub nazwisko</option>
            <option value="phone">Telefon</option>
            <option value="pesel">PESEL</option>
        </select>
        <div class="input-group-append search-button">
            <button class="btn btn-primary" type="submit">Szukaj</button>
        </div>
    </div>
</form>
</div>

      <table class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Opcje</th>
                    <th scope="col">Imię i nazwisko</th>
                    <th scope="col">PESEL</th>
                    <th scope="col">Email</th>
                    <th scope="col">Telefon</th>
                    <th scope="col">Czy aktywny</th>
                    <th scope="col">Typ konta</th>
                </tr>
            </thead>
            <tbody>

            {% for user_profile in users_profiles_list %}
                    <tr>
                        <td>
                            <!-- Profil usera -->
                            {% if user.is_superuser %}
                                <a href="{% url 'accounts:user_detail' pk=user_profile.user.pk %}"><img src="{% static 'website_icons/info_ico.png' %}" alt="Szczegóły" width="20" height="20"></a>
                            {% endif %}

                            <!-- Aktywowanie usera -->
                            {% if user.is_superuser and user_profile.user.is_active == False %}
                                <a href="{% url 'accounts:user_activate' pk=user_profile.pk %}"><img src="{% static 'website_icons/activate_user_ico.png' %}" alt="Aktywuj konto" width="20" height="20"></a>
                            {% endif %}

                            
                            
                            <!-- Dezaktywowanie usera -->
                            {% if user_profile.user.is_active == True and user_profile.user.is_superuser == False %}
                                <a href="{% url 'accounts:user_deactivate' pk=user_profile.pk %}"><img src="{% static 'website_icons/deactivate_user_ico.png' %}" alt="Usuń konto" width="20" height="20"></a> 
                            {% endif %}

                            <!-- Nadanie praw superusera -->
                            {% if user_profile.user.is_active == True and user_profile.user.is_superuser == False %}
                                <a href="{% url 'accounts:user_grant' pk=user_profile.pk %}"><img src="{% static 'website_icons/grant_ico.png' %}" alt="Nadaj uprawnienia bibliotekrza" width="20" height="20"></a>
                            {% endif %}
                            
                            <!-- Odebranie praw superusera -->
                            {% if user.id is not user_profile.user.id and user_profile.user.is_active == True and user_profile.user.is_superuser == True %}
                                <a href="{% url 'accounts:get_rights' pk=user_profile.pk %}"><img src="{% static 'website_icons/get_rights_ico.png' %}" alt="Odebranie uprawnienia bibliotekrza" width="20" height="20"></a>
                            {% endif %}
                        </td>

                        <td>{{user_profile.user.get_full_name}}</td>
                        <td>{{user_profile.pesel}}</td>
                        <td>{{user_profile.user.email}}</td>
                        <td>{{user_profile.phone}}</td>
                        

                        <td>
                            {% if user_profile.user.is_active %}
                                Tak
                            {% else %}
                                Nie
                            {% endif %}
                        </td>

                        <td>
                            {% if user_profile.user.is_superuser %}
                                Kierownik
                            {% else %}
                                Pracownik
                            {% endif %}
                        </td>
                        
                    </tr>
            {% endfor %}
            </tbody>
        </table>

    <!-- pagination bar -->
    <div class="pagination_bar">
        {% if is_paginated %}
        <div class="btn-group pagination_bar" role="group">
            
            {% if page_obj.has_previous %}
                <a class="btn btn-light disable" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            {% else %}
                <a class="btn btn-light"><span>&laquo;</span></a>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <a  class="btn btn-dark active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
                {% else %}
                <a class="btn btn-light" href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
                
            {% if page_obj.has_next %}
            <a class="btn btn-light" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            {% else %}
            <a type="button" class="btn btn-light"><span>&raquo;</span></a>
            {% endif %}
        </div>
        {% endif %}
    </div>

    <div class="table-legend">
        <p><b>Legenda:</b></p>
        <p><img src="{% static 'website_icons/info_ico.png' %}" alt="Szczegóły" width="20" height="20">Zobacz profil</p>
        <p><img src="{% static 'website_icons/deactivate_user_ico.png' %}" alt="Usuń wypozyczenie" width="20" height="20">Dezaktywwuj konto</p>
        <p><img src="{% static 'website_icons/activate_user_ico.png' %}" alt="Aktywuj użytkownika" width="20" height="20">Aktywuj konto</p>
        <p><img src="{% static 'website_icons/grant_ico.png' %}" alt="Nadaj uprawnienia" width="20" height="20">Nadaj uprawnienia</p>
        <p><img src="{% static 'website_icons/get_rights_ico.png' %}" alt="Odbierz uprawnienia" width="20" height="20">Odbierz uprawnienia</p>
    </div>

</div>

{% endblock %}