ems_app/urls.py
from django.urls import path

from ems_app import views

app_name = 'ems_app'

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
]

ems_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from ems_app.views import NoPermsPage
from accounts.views import UserAutocomplete, UserAdminsAutocomplete
from django_private_chat import urls as django_private_chat_urls



urlpatterns = [
    path('', include('ems_app.urls')),
    path('projects/', include('project_app.urls')),
    path('holiday/', include('holiday_app.urls')),
    path('resources/', include('resources_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('msg/', include('django_private_chat.urls')),
    path('no-permission/', NoPermsPage.as_view(), name="no_permission"),
    path('user-autocomplete/', UserAutocomplete.as_view(),name='user_autocomplete'),
    path('user-admin-autocomplete/', UserAdminsAutocomplete.as_view(),name='user_admin_autocomplete'),
] 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_app/urls.py
from django.urls import path
from project_app import views

app_name = 'project_app'

urlpatterns = [
    path('show/', views.ProjectListView.as_view(), name='projects_list'),
    path('new_project/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project_update'),
]

project_app/models.py
from django.db import models
from accounts.models import MyUser

# Create your models here.

class ProjectModel(models.Model):
    id_employee = models.ManyToManyField(MyUser,  verbose_name='Pracownik', related_name='project_employee_user')
    id_project_pm = models.ForeignKey(MyUser, on_delete=models.DO_NOTHING, verbose_name='Manager projektu', related_name='project_pm_user', null=True, blank=True)
    client = models.CharField(max_length=300, verbose_name='Nazwa klienta')
    name = models.CharField(max_length=200, verbose_name='Nazwa')
    number = models.IntegerField(verbose_name='Numer projektu')
    number_2 = models.IntegerField(verbose_name='Numer projektu 2')
    project_type = models.CharField(max_length=50, verbose_name='Typ projektu')
    status = models.CharField(max_length=50, verbose_name='Status')
    start_date = models.DateField(verbose_name='Data rozpoczęcia')
    end_date = models.DateField(verbose_name='Data zakończenia')
    contact = models.CharField(max_length=500, verbose_name='Kontakt')
    commants = models.TextField(max_length=500, verbose_name='Uwagi', null=True, blank=True)

    def __str__(self):
        return self.name+" number: "+ str(self.number) +" number2: " + str(self.number_2) + " project_pm: " + self.id_project_pm.get_full_name()

project_app/forms.py
from django import forms
from project_app import models
from flatpickr import DatePickerInput, TimePickerInput, DateTimePickerInput
from dal import autocomplete

class ProjectForm(forms.ModelForm):
    class Meta:
        model = models.ProjectModel
        fields = '__all__'
        widgets = {
            'id_employee': autocomplete.ModelSelect2Multiple(
                url='user_autocomplete',
                attrs={
                    'data-minimum-input-length': 3,
                    },
                ),

            'start_date': DatePickerInput(options = { "dateFormat": "d.m.y",}),
            'end_date': DatePickerInput(options = { "dateFormat": "d.m.y",}),
        }

    def clean(self):
        start_date = self.cleaned_data.get("start_date")
        end_date = self.cleaned_data.get("end_date")
        print(start_date, end_date)
        if end_date < start_date:
            msg = "Data rozpoczęcia jest póżniejsza niż data zakończenia"
            self._errors["end_date"] = self.error_class([msg])

project_app/views.py
from django.views.generic import TemplateView, ListView, DetailView, DeleteView, CreateView, UpdateView
from braces.views import SuperuserRequiredMixin, LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from project_app import models
from project_app import forms
from django.db.models import Q

# Create your views here.

class ProjectListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = models.ProjectModel
    paginate_by = 10
    template_name = 'projects/project_list.html'
    context_object_name = 'user_projects_list'

    def get_queryset(self):
        user = self.request.user
        qs = super().get_queryset()
        search_query = self.request.GET.get("search_query")
        search_type = self.request.GET.get("search_type")

        if(user.is_superuser == False):
            qs = qs.filter( Q(id_employee=user.id) | Q(id_project_pm=user.id) )

        if search_query is not None:
            if search_type == "name":
                qs = qs.filter( Q(name__icontains=search_query) )
            if search_type == "client":
                qs = qs.filter( Q(client__icontains=search_query) )
            elif search_type == "number":
                qs = qs.filter( Q(number__icontains=search_query) | Q(number_2__icontains=search_query) )
            elif search_type == "PM":
                qs = qs.filter( Q(id_project_pm__first_name__icontains=search_query) | Q(id_project_pm__last_name__icontains=search_query) )

        qs = qs.order_by('end_date')
        return qs

class ProjectDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = models.ProjectModel
    context_object_name = "user_project"
    template_name = 'projects/project_detail.html'

class ProjectDeleteView(LoginRequiredMixin, SuperuserRequiredMixin, DeleteView):
    login_url = reverse_lazy('accounts:login')
    model = models.ProjectModel
    success_url = reverse_lazy("project_app:projects_list")

    context_object_name = "user_project"
    template_name = 'projects/project_delete.html'

class ProjectUpdateView(LoginRequiredMixin, SuperuserRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = models.ProjectModel
    success_url = reverse_lazy("project_app:projects_list")

    context_object_name = "project"
    form_class = forms.ProjectForm
    template_name = 'projects/project_update.html'


class ProjectCreateView(LoginRequiredMixin, SuperuserRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    success_url = reverse_lazy("project_app:projects_list")

    form_class = forms.ProjectForm
    model = models.ProjectModel
    template_name = 'projects/project_create.html'


    
    

project_app/templates/projects/project_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head_block %}
    {{ form.media }}
{% endblock %}

{% block body_block %}

<div class="container">
    <h1 class="page-title">Utwórz projekt</h1>

    <form method="POST" action="{% url 'project_app:project_create' %}" class="create-view">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-center">
            <input type="submit" value="Utwórz" class="btn-action btn btn-primary btn-large">
        </div>
    </form>
</div>

{% endblock %}

project_app/templates/projects/project_delete.html
{% extends "base.html" %}

{% block body_block %}

<div class="container">
    <h2 class="page-title">Czy chcesz usunąć projekt?</h2>
    <h4>Szczegóły</h4>
    <div>
            <ul>
                <li><b>Nazwa: </b> {{user_project.name}} </li>
                <li><b>Klient: </b> {{user_project.client}} </li>
                <li><b>Kontakt: </b> {{user_project.contact}} </li>
                <li><b>Numer: </b> {{user_project.number}} </li>
                <li><b>Numer2: </b> {{user_project.number_2}} </li>
                <li><b>Status: </b> {{user_project.status}} </li>
                <li><b>PM: </b> {{user_project.id_project_pm.get_full_name}} </li>
                <li>
                    <b>Pracownicy: </b>
                    {% for employee in user_project.id_employee.all %}
                        {{employee.get_full_name}}
                    {% endfor %}
                </li>

                <li><b>Uwagi: </b> {{user_project.commants|safe|linebreaksbr}} </li>
            </ul>               
        </div>

        <form method="POST">
            {% csrf_token %}
            <a class="btn btn-dark" href="javascript:history.back()">Powrót</a>
            <input type="submit" class="btn btn-danger" value="Usuń">
        </form>
</div>
{% endblock %}

project_app/templates/projects/project_detail.html
{% extends "base.html" %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <div class="page-title">
            <h2>Szczegóły projektu </h2>
        </div>
        <div class="detail-view-content">
            <ul>
                <li><b>Nazwa: </b> {{user_project.name}} </li>
                <li><b>Klient: </b> {{user_project.client}} </li>
                <li><b>Kontakt: </b> {{user_project.contact}} </li>
                <li><b>Numer: </b> {{user_project.number}} </li>
                <li><b>Numer2: </b> {{user_project.number_2}} </li>
                <li><b>Status: </b> {{user_project.status}} </li>
                <li><b>PM: </b> {{user_project.id_project_pm.get_full_name}} </li>
                <li>
                    <b>Pracownicy: </b>
                    {% for employee in user_project.id_employee.all %}
                        {{employee.get_full_name}}
                    {% endfor %}
                </li>

                <li><b>Uwagi: </b><br> {{user_project.commants|safe|linebreaksbr}} </li>
            </ul>               
        </div>
        <a class="detail-view-btn btn btn-dark" href="javascript:history.back()">Powrót</a>

    </div>    
</div>
{% endblock %}

project_app/templates/projects/project_list.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% load ems_extras %}

{% block body_block %}

<div class="container">
    <div class="page-title">
        <h2>Projekty</h2>
    </div>

    {% if user.is_superuser %}
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'project_app:project_create' %}">Dodaj projekt</a>
        </div>
    {% endif %}


    <div class="search-bar">
    <form class="form-inline" action="{% url 'project_app:projects_list' %}" method="GET">
        <div class="input-group">
            <input type="search" class="form-control" name="search_query" placeholder="Wyszukaj">
            <select class="search-select" name="search_type">
                <option value="name" selected>Nazwa</option>
                <option value="client" selected>Klient</option>
                <option value="number">Numer</option>
                <option value="PM">PM</option>
            </select>
            <div class="input-group-append search-button">
                <button class="btn btn-primary" type="submit">Szukaj</button>
            </div>
        </div>
    </form>
    </div>

      <table class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Opcje</th>
                    <th scope="col">Lp.</th>
                    <th scope="col">Nazwa</th>
                    <th scope="col">Klient</th>
                    <th scope="col">PM</th>
                    <th scope="col">Numer</th>
                    <th scope="col">Status</th>
                    <th scope="col">Data rozpoczęcia</th>
                    <th scope="col">Data zakończenia</th>
                </tr>
            </thead>
            <tbody>
                {% for project in user_projects_list %}
                <tr>
                    <td>
                        <a href="{% url 'project_app:project_detail' pk=project.pk %}"><img src="{% static 'website_icons/info_ico.png' %}" alt="Szczegóły" width="20" height="20"></a>
                        {% if user.is_superuser %}
                            <a href="{% url 'project_app:project_delete' pk=project.pk %}"><img src="{% static 'website_icons/del_ico.png' %}" alt="Usuń" width="20" height="20"></a>
                            <a href="{% url 'project_app:project_update' pk=project.pk %}"><img src="{% static 'website_icons/edit_ico.png' %}" alt="Edytuj" width="20" height="20"></a>
                        {% endif %}
                    </td>
                    
                    <td>{{ forloop.counter }}</td>
                    <td>{{project.name|check_empty}}</td>
                    <td>{{project.client|check_empty}}</td>
                    <td>{{project.id_project_pm.get_full_name|check_empty}}</td>
                    <td>{{project.number|check_empty}}</td>
                    <td>{{project.status|check_empty}}</td>
                    <td>{{project.start_date|check_empty}}</td>
                    <td>{{project.end_date|check_empty}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    <!-- pagination bar -->
    <div class="pagination_bar">
        {% if is_paginated %}
        <div class="btn-group pagination_bar" role="group">
            
            {% if page_obj.has_previous %}
                <a class="btn btn-light disable" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            {% else %}
                <a class="btn btn-light"><span>&laquo;</span></a>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <a  class="btn btn-dark active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
                {% else %}
                <a class="btn btn-light" href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
                
            {% if page_obj.has_next %}
            <a class="btn btn-light" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            {% else %}
            <a type="button" class="btn btn-light"><span>&raquo;</span></a>
            {% endif %}
        </div>
        {% endif %}
    </div>

    <div class="table-legend">
        <p><b>Legenda:</b></p>
        <p><img src="{% static 'website_icons/info_ico.png' %}" alt="Szczegóły" width="20" height="20">Szczegóły projektu</p>
        {% if user.is_superuser %}
            <p><img src="{% static 'website_icons/del_ico.png' %}" alt="Szczegóły" width="20" height="20">Usuń projekt</p>
            <p><img src="{% static 'website_icons/edit_ico.png' %}" alt="Szczegóły" width="20" height="20">Edytuj projekt</p>
        {% endif %}
    </div>

</div>

{% endblock body_block %}

project_app/templates/projects/project_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head_block %}
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

    {{ form.media }}

{% endblock %}

{% block body_block %}
<div class="container">
    <h1>Edytuj projekt</h1>
    <form method="POST" action="{% url 'project_app:project_update' pk=project.pk %}" class="update-form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-center">
            <input type="submit" value="Uaktualnij" class="btn-action btn btn-primary btn-large">
        </div>
    </form>
</div>
{% endblock %}