accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [ #wiazanie widoku z django z templatka login.html
    path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'), #idzie do homepage
    path('signup/', views.register, name='signup'),
    path('after_signup/', views.AfterRegisterPage.as_view(), name="after_signup"),

    path('password_reset/',  
            auth_views.PasswordResetView.as_view(template_name="accounts/password_reset_form.html"), 
            name='password_reset'
        ),

    path('password_reset/done/',
            auth_views.PasswordResetDoneView.as_view(template_name= "accounts/password_reset_done.html"), 
            name='password_reset_done'
        ),
    
    path('accounts/reset_password_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='reset_password_confirm'),

    path('reset/done/',
            auth_views.PasswordResetCompleteView.as_view(template_name= "accounts/password_reset_complete.html"), 
            name='password_reset_complete'
        ),

    path('my_profile/', views.MyProfileTemplateView.as_view(), name='my_profile'),
    path('my_profile_update/<int:pk>/', views.UpdateMyProfileView.as_view(), name='my_profile_update'),


    path('users_list/', views.UsersListView.as_view(), name='users_list'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('user_grant/<int:pk>/', views.UserGrantDetailView.as_view(), name='user_grant'),
    path('user_activate/<int:pk>/', views.UserActivateDetailView.as_view(), name='user_activate'),
    path('user_deactivate/<int:pk>/', views.UserDeactivateDetailView.as_view(), name='user_deactivate'),
    path('get_rights/<int:pk>/', views.UserGetRightsDetailView.as_view(), name='get_rights'),
]  

ems_app/urls.py
from django.urls import path

from ems_app import views

app_name = 'ems_app'

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
]

ems_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from ems_app.views import NoPermsPage
from accounts.views import UserAutocomplete, UserAdminsAutocomplete
from django_private_chat import urls as django_private_chat_urls



urlpatterns = [
    path('', include('ems_app.urls')),
    path('projects/', include('project_app.urls')),
    path('holiday/', include('holiday_app.urls')),
    path('resources/', include('resources_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('msg/', include('django_private_chat.urls')),
    path('no-permission/', NoPermsPage.as_view(), name="no_permission"),
    path('user-autocomplete/', UserAutocomplete.as_view(),name='user_autocomplete'),
    path('user-admin-autocomplete/', UserAdminsAutocomplete.as_view(),name='user_admin_autocomplete'),
] 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

holiday_app/urls.py
from django.urls import path
from holiday_app import views

app_name = 'holiday_app'

urlpatterns = [
    path('show/', views.HolidayListView.as_view(), name='holidays_list'),
    path('new_holiday/', views.HolidayCreateView.as_view(), name='holiday_create'),
    path('<int:pk>', views.HolidayDetailView.as_view(), name='holiday_detail'),
    path('<int:pk>/delete/', views.HolidayDeleteView.as_view(), name='holiday_delete'),
    path('<int:pk>/edit/', views.HolidayUpdateView.as_view(), name='holiday_update'),
]

project_app/urls.py
from django.urls import path
from project_app import views

app_name = 'project_app'

urlpatterns = [
    path('show/', views.ProjectListView.as_view(), name='projects_list'),
    path('new_project/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project_update'),
]

resources_app/urls.py
from django.urls import path
from resources_app import views

app_name = 'resources_app'

urlpatterns = [
    path('show/', views.ResourceListView.as_view(), name='resources_list'),
    path('new_resource/', views.ResourceCreateView.as_view(), name='resource_create'),
    # path('<int:pk>', views.ResourceDetailView.as_view(), name='resource_detail'),
    # path('<int:pk>/delete/', views.ResourceDeleteView.as_view(), name='resource_delete'),
    # path('<int:pk>/edit/', views.ResourceUpdateView.as_view(), name='resource_update'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load bootstrap4 %}

<head>
    <meta charset="UTF-8">
    <title>EMS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Employee Management System">

    <link href="https://use.fontawesome.com/releases/v5.9.0/css/all.css" rel="stylesheet">

    <!-- Bootstrap4 -->
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/style-bootstrap.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

    {% block head_block %}{% endblock %}

    <script>
    jQuery(function($) {

    $(".sidebar-dropdown > a").click(function() {
        $(".sidebar-submenu").slideUp(200);
        if ($(this).parent().hasClass("active")) {
            $(".sidebar-dropdown").removeClass("active");
            $(this).parent().removeClass("active");
        } else {
            $(".sidebar-dropdown").removeClass("active");
            $(this).next(".sidebar-submenu").slideDown(200);
            $(this).parent().addClass("active");
        }
    });

    $("#close-sidebar").click(function() {
        $(".page-wrapper").removeClass("toggled");
    });

    $("#show-sidebar").click(function() {
        $(".page-wrapper").addClass("toggled");
    });
    });
    </script>

</head>

<body>

{% if user.is_authenticated %}
      <div class="page-wrapper chiller-theme toggled">
        <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
          <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar" class="sidebar-wrapper">
          <div class="sidebar-content">
            <div class="sidebar-brand">
              <a href="{% url 'ems_app:index' %}">EMS</a>
              <div id="close-sidebar">
                <i class="fas fa-times"></i>
              </div>
            </div>

            <div class="sidebar-header">
              <div class="user-pic">
                  {% if user.user_profile.image %}
                      <img class="img-responsive img-rounded" src="{{user.user_profile.image.url}}" alt="User picture">
                  {% else %}
                      <img class="img-responsive img-rounded" src="{% static '/img/default_user_img.png' %}" alt="User picture">
                  {% endif %}
              </div>

              <div class="user-info">
                <span class="user-name">{{ user.first_name }}
                  <strong>{{ user.last_name }}</strong>
                </span>

                <span class="user-role">
                  {% if user.is_superuser %}
                      Administrator
                  {% else %}
                      Użytkownik
                  {% endif %}
                </span>

              </div>
            </div>
            <div class="sidebar-menu">
              <ul>
                <li class="header-menu">
                  <span>Menu</span>
                </li>

                <li>
                  <a href="{% url 'ems_app:index' %}">
                    <i class="fa fa-warehouse"></i>
                    <span>Dashboard</span>
                  </a>
                </li>

    
                 <li class="sidebar-dropdown">
                    <a>
                      <i class="fa fa-file-alt"></i>
                      <span>Projekty</span>
                    </a>
                    <div class="sidebar-submenu">
                      <ul>
                        <li>
                          <a href="{% url 'project_app:projects_list' %}">Lista projetków</a>
                        </li>
                        {% if user.is_superuser %}
                          <li>
                            <a href="{% url 'project_app:project_create' %}">Dodaj projekt</a>
                          </li>
                        {% endif %}
                      </ul>
                    </div>
                </li>

                <li class="sidebar-dropdown">
                  <a>
                    <i class="fa fa-sun"></i>
                    <span>Urlopy</span>
                  </a>
                  <div class="sidebar-submenu">
                    <ul>
                      <li>
                        <a href="{% url 'holiday_app:holidays_list' %}">Lista urlopów</a>
                      </li>
                      {% if user.is_superuser %}
                        <li>
                          <a href="{% url 'holiday_app:holiday_create' %}">Dodaj urlop</a>
                        </li>
                      {% endif %}
                    </ul>
                  </div>
                </li>

                <li class="sidebar-dropdown">
                    <a>
                      <i class="fa fa-car"></i>
                      <span>Zasoby</span>
                    </a>
                    <div class="sidebar-submenu">
                      <ul>
                        <li>
                          <a href="{% url 'resources_app:resources_list' %}">Lista zasobów</a>
                        </li>
                        {% if user.is_superuser %}
                          <li>
                            <a href="{% url 'resources_app:resource_create' %}">Dodaj zasób</a>
                          </li>
                        {% endif %}
                      </ul>
                    </div>
                  </li>
  


                <li class="sidebar-dropdown">
                  <a href="#">
                    <i class="fa fa-chart-line"></i>
                    <span>Charts</span>
                  </a>
                  <div class="sidebar-submenu">
                    <ul>
                      <li>
                        <a href="#">Pie chart</a>
                      </li>
                      <li>
                        <a href="#">Line chart</a>
                      </li>
                      <li>
                        <a href="#">Bar chart</a>
                      </li>
                      <li>
                        <a href="#">Histogram</a>
                      </li>
                    </ul>
                  </div>
                </li>
                <li class="sidebar-dropdown">
                  <a href="#">
                    <i class="fa fa-globe"></i>
                    <span>Maps</span>
                  </a>
                  <div class="sidebar-submenu">
                    <ul>
                      <li>
                        <a href="#">Google maps</a>
                      </li>
                      <li>
                        <a href="#">Open street map</a>
                      </li>
                    </ul>
                  </div>
                </li>
                <li class="header-menu">
                  <span></span>
                </li>

                {% if user.user_profile %}
                  <li class="sidebar-dropdown">
                      <a>
                        <i class="fa fa-users"></i>
                        <span>Twój profil</span>
                      </a>
                      <div class="sidebar-submenu">
                        <ul>
                          <li>
                            <a href="{% url 'accounts:my_profile' %}">Wyświetl profil</a>
                          </li>
                          <li>
                            <a href="{% url 'accounts:my_profile_update' pk=user.user_profile.id %}">Edytuj profil</a>
                          </li>
                          <li>
                            <a href="{% url 'accounts:password_reset' %}">Zresetuj hasło</a>
                          </li>
                        </ul>
                      </div>
                    </li>
                {% endif %}

                {% if user.is_authenticated and user.is_superuser %}
                <li>
                  <a href="{% url 'admin:index' %}">
                    <i class="fa fa-cog"></i>
                    <span>Panel administratora</span>
                  </a>
                </li>

                <li class="sidebar-dropdown">
                    <a>
                      <i class="fa fa-user-shield"></i>
                      <span>Zarządzaj użytkownikami</span>
                    </a>
                    <div class="sidebar-submenu">
                      <ul>
                        <li>
                          <a href="{% url 'accounts:users_list' %}">Lista użytkowników</a>
                        </li>
                        <li>
                          <a href="{% url 'accounts:signup' %}">Utwórz konto użytkownika</a>
                        </li>
                      </ul>
                    </div>
                  </li>
                {% endif %}

                <li>
                  <a href="{% url 'accounts:logout' %}">
                    <i class="fa fa-sign-out-alt"></i>
                    <span>Wyloguj</span>
                  </a>
                </li>
                
              </ul>
            </div>
            <!-- sidebar-menu  -->
          </div>
        </nav>
{% endif %}
  
  <!-- sidebar-wrapper  -->
  <main class="page-content">
    <div class="container-fluid">
        {% block body_block %}{% endblock %}
    </div>
  </main>
  <!-- page-content" -->
</div>
<!-- page-wrapper -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    
</body>

</html>

templates/no_perms.html
{% extends "base.html" %}

{% block body_block %}
    <div class="container">
        <h2 class="page-title">Strona dostępna tylko dla administratora.</h2>
    </div>
{% endblock %}