ems_app/urls.py
from django.urls import path

from ems_app import views

app_name = 'ems_app'

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
]

ems_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from ems_app.views import NoPermsPage
from accounts.views import UserAutocomplete, UserAdminsAutocomplete
from django_private_chat import urls as django_private_chat_urls



urlpatterns = [
    path('', include('ems_app.urls')),
    path('projects/', include('project_app.urls')),
    path('holiday/', include('holiday_app.urls')),
    path('resources/', include('resources_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('msg/', include('django_private_chat.urls')),
    path('no-permission/', NoPermsPage.as_view(), name="no_permission"),
    path('user-autocomplete/', UserAutocomplete.as_view(),name='user_autocomplete'),
    path('user-admin-autocomplete/', UserAdminsAutocomplete.as_view(),name='user_admin_autocomplete'),
] 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

holiday_app/urls.py
from django.urls import path
from holiday_app import views

app_name = 'holiday_app'

urlpatterns = [
    path('show/', views.HolidayListView.as_view(), name='holidays_list'),
    path('new_holiday/', views.HolidayCreateView.as_view(), name='holiday_create'),
    path('<int:pk>', views.HolidayDetailView.as_view(), name='holiday_detail'),
    path('<int:pk>/delete/', views.HolidayDeleteView.as_view(), name='holiday_delete'),
    path('<int:pk>/edit/', views.HolidayUpdateView.as_view(), name='holiday_update'),
]

holiday_app/models.py
from django.db import models
from accounts.models import MyUser

# Create your models here.
class HolidayModel(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.DO_NOTHING, verbose_name='Pracownik', related_name='holiday_user')
    approver_user = models.ForeignKey(MyUser, on_delete=models.DO_NOTHING,  null=True, blank=True, default=None, verbose_name='Osoba zatwierdzająca', related_name='holiday_approver_user')
    start_date = models.DateField(verbose_name='Data rozpoczęcia')
    end_date = models.DateField(verbose_name='Data zakończenia')
    is_used = models.BooleanField(default=False, verbose_name='Czy zakończone')
    is_approved = models.BooleanField(default=False, verbose_name='Czy zatwierdzone')

    def __str__(self):
        return "Wolne: " + self.user.get_full_name() + " PESEL: " + self.user.user_profile.pesel + "  od: " + str(self.start_date) + " do: " + str(self.end_date)

holiday_app/forms.py
from django import forms
from holiday_app import models
from flatpickr import DatePickerInput, TimePickerInput, DateTimePickerInput
from dal import autocomplete

class HolidayForm(forms.ModelForm):
    class Meta:
        model = models.HolidayModel
        fields = '__all__'
        widgets = {
            'approver_user': autocomplete.ModelSelect2(
                url='user_admin_autocomplete',
                attrs={
                    'data-minimum-input-length': 3,
                    },
                ),

            'start_date': DatePickerInput(options = { "dateFormat": "d.m.y",}),
            'end_date': DatePickerInput(options = { "dateFormat": "d.m.y",}),
        }

    def __init__(self, user, *args, **kwargs):
        #jesli user nie jest adminem to moze zaplanowac urlop tylko sobie, i nie ma pol
        #w widoku trzeba przeslonic metode get_form_kwargs() aby dodac usera do formularza
        super(HolidayForm, self).__init__(*args, **kwargs)
        if user.is_superuser == False:
            self.fields['user'].queryset = models.MyUser.objects.filter(id=user.id)
            self.fields.pop('is_used')
            self.fields.pop('is_approved')
        else:
            self.fields.pop('is_used')


    def clean(self):
        start_date = self.cleaned_data.get("start_date")
        end_date = self.cleaned_data.get("end_date")
        print(start_date, end_date)
        if end_date < start_date:
            msg = "Data rozpoczęcia jest póżniejsza niż data zakończenia"
            self._errors["end_date"] = self.error_class([msg])



class HolidayUpdateForm(forms.ModelForm):
    class Meta:
        model = models.HolidayModel
        fields = '__all__'
        widgets = {
            'approver_user': autocomplete.ModelSelect2(
                url='user_admin_autocomplete',
                attrs={
                    'data-minimum-input-length': 3,
                    },
                ),

            'start_date': DatePickerInput(options = { "dateFormat": "d.m.y",}),
            'end_date': DatePickerInput(options = { "dateFormat": "d.m.y",}),
        }


    def clean(self):
        start_date = self.cleaned_data.get("start_date")
        end_date = self.cleaned_data.get("end_date")
        print(start_date, end_date)
        if end_date < start_date:
            msg = "Data rozpoczęcia jest póżniejsza niż data zakończenia"
            self._errors["end_date"] = self.error_class([msg])

holiday_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, DeleteView, CreateView, UpdateView
from braces.views import SuperuserRequiredMixin, LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from holiday_app import models
from holiday_app import forms
from django.db.models import Q
import datetime

# Create your views here.

class HolidayListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = models.HolidayModel
    paginate_by = 10
    template_name = 'holiday/holiday_list.html'
    context_object_name = 'holiday_list'

    def get_queryset(self):
        user = self.request.user
        qs = super().get_queryset()
        date_year = self.request.GET.get("search_query")
        search_type = self.request.GET.get("search_type")

        if(user.is_superuser == False):
            qs = qs.filter( Q(user_id=user.id) )

        if date_year is not None:
            if search_type == "year":
                qs = qs.filter( Q(start_date__icontains=date_year) | Q(end_date__icontains=date_year) )
        
        qs = qs.order_by('start_date')

        return qs

class HolidayCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    success_url = reverse_lazy("holiday_app:holidays_list")

    form_class = forms.HolidayForm
    
    model = models.HolidayModel
    template_name = 'holiday/holiday_create.html'

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super(HolidayCreateView, self).get_form_kwargs(*args, **kwargs)
        form_kwargs['user'] = self.request.user
        return form_kwargs

class HolidayDeleteView(LoginRequiredMixin, SuperuserRequiredMixin, DeleteView):
    login_url = reverse_lazy('accounts:login')
    model = models.HolidayModel
    success_url = reverse_lazy("holiday_app:holidays_list")

    context_object_name = "holiday"
    template_name = 'holiday/holiday_delete.html'

class HolidayDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = models.HolidayModel
    context_object_name = "holiday"
    template_name = 'holiday/holiday_detail.html'

class HolidayUpdateView(LoginRequiredMixin, SuperuserRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = models.HolidayModel
    success_url = reverse_lazy("holiday_app:holidays_list")

    context_object_name = "holiday"
    form_class = forms.HolidayUpdateForm
    template_name = 'holiday/holiday_update.html'

holiday_app/templates/holiday/holiday_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head_block %}
    {{ form.media }}
{% endblock %}

{% block body_block %}

<div class="container">
    <h1 class="page-title">Utwórz urlop</h1>

    <form method="POST" action="{% url 'holiday_app:holiday_create' %}" class="create-view">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-center">
            <input type="submit" value="Utwórz" class="btn-action btn btn-primary btn-large">
        </div>
    </form>
</div>

{% endblock %}

holiday_app/templates/holiday/holiday_delete.html
{% extends "base.html" %}

{% block body_block %}

<div class="container">
    <h2 class="page-title">Czy chcesz usunąć urlop?</h2>
    <h4>Szczegóły</h4>
    <div>
            <ul>
                <li><b>Pracownik: </b> {{holiday.user.get_full_name}} </li>
                <li><b>Osoba zatwierdzająca: </b> {{holiday.approver_user.get_full_name}} </li>
                <li><b>Data rozpoczęcia: </b> {{holiday.start_date}} </li>
                <li><b>Data zakończenia: </b> {{holiday.end_date}} </li>
                <li><b>Czy wykorzystane: </b> {% if holiday.is_used %} Tak {% else %} Nie {% endif %} </li>
                <li><b>Czy zatwierdzone: </b> {% if holiday.is_approved %} Tak {% else %} Nie {% endif %} </li>
            </ul>               
    </div>

        <form method="POST">
            {% csrf_token %}
            <a class="btn btn-dark" href="javascript:history.back()">Powrót</a>
            <input type="submit" class="btn btn-danger" value="Usuń">
        </form>
</div>
{% endblock %}

holiday_app/templates/holiday/holiday_detail.html
{% extends "base.html" %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <div class="page-title">
            <h2>Szczegóły urlopu </h2>
        </div>
        <div class="detail-view-content">
            <ul>
                <li><b>Pracownik: </b> {{holiday.user.get_full_name}} </li>
                <li><b>Osoba zatwierdzająca: </b> {{holiday.approver_user.get_full_name}} </li>
                <li><b>Data rozpoczęcia: </b> {{holiday.start_date}} </li>
                <li><b>Data zakończenia: </b> {{holiday.end_date}} </li>
                <li><b>Czy wykorzystane: </b> {% if holiday.is_used %} Tak {% else %} Nie {% endif %} </li>
                <li><b>Czy zatwierdzone: </b> {% if holiday.is_approved %} Tak {% else %} Nie {% endif %} </li>
            </ul>              
        </div>
        <a class="detail-view-btn btn btn-dark" href="javascript:history.back()">Powrót</a>

    </div>    
</div>
{% endblock %}

holiday_app/templates/holiday/holiday_list.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% load ems_extras %}

{% block body_block %}

<div class="container">
    <div class="page-title">
        <h2>Urlopy</h2>
    </div>
    
    {% if user.is_superuser %}
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'holiday_app:holiday_create' %}">Dodaj urlop</a>
        </div>
    {% endif %}

    <div class="search-bar">
    <form class="form-inline" action="" method="GET">
        <div class="input-group">
            <input type="search" class="form-control" name="search_query" placeholder="Wyszukaj" required>
            <select class="search-select" name="search_type">
                <option value="year" selected>Rok</option>
            </select>
            <div class="input-group-append search-button">
                <button class="btn btn-primary" type="submit">Szukaj</button>
            </div>
        </div>
    </form>
    </div>

      <table class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Opcje</th>
                    <th scope="col">Lp.</th>
                    <th scope="col">Pracownik</th>
                    <th scope="col">Data rozpoczęcia</th>
                    <th scope="col">Data zakończenia</th>
                    <th scope="col">Czy zatwierdzony</th>
                    <th scope="col">Osoba zatwierdzająca</th>
                </tr>
            </thead>
            <tbody>
                {% for holiday in holiday_list %}
                <tr>
                    <td>
                            <a href="{% url 'holiday_app:holiday_detail' pk=holiday.pk %}"><img src="{% static 'website_icons/info_ico.png' %}" alt="Szczegóły" width="20" height="20"></a>
                        {% if user.is_superuser %}
                            <a href="{% url 'holiday_app:holiday_delete' pk=holiday.pk %}"><img src="{% static 'website_icons/del_ico.png' %}" alt="Usuń" width="20" height="20"></a>
                            <a href="{% url 'holiday_app:holiday_update' pk=holiday.pk %}"><img src="{% static 'website_icons/edit_ico.png' %}" alt="Edytuj" width="20" height="20"></a>
                        {% endif %}
                    </td>
                    
                    <td>{{ forloop.counter }}</td>
                    <td>{{holiday.user.get_full_name}}</td>
                    <td>{{holiday.start_date|check_empty}}</td>
                    <td>{{holiday.end_date|check_empty}}</td>
                    <td>{% if holiday.is_approved %} Tak {% else %} Nie {% endif %}</td>
                    <td>{{holiday.approver_user.get_full_name}} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    <!-- pagination bar -->
    <div class="pagination_bar">
        {% if is_paginated %}
        <div class="btn-group pagination_bar" role="group">
            
            {% if page_obj.has_previous %}
                <a class="btn btn-light disable" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            {% else %}
                <a class="btn btn-light"><span>&laquo;</span></a>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <a  class="btn btn-dark active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
                {% else %}
                <a class="btn btn-light" href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
                
            {% if page_obj.has_next %}
            <a class="btn btn-light" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            {% else %}
            <a type="button" class="btn btn-light"><span>&raquo;</span></a>
            {% endif %}
        </div>
        {% endif %}
    </div>

    <div class="table-legend">
        <p><b>Legenda:</b></p>
        <p><img src="{% static 'website_icons/info_ico.png' %}" alt="Szczegóły" width="20" height="20">Szczegóły urlopu</p>
        {% if user.is_superuser %}
            <p><img src="{% static 'website_icons/del_ico.png' %}" alt="Usuń" width="20" height="20">Usuń urlop</p>
            <p><img src="{% static 'website_icons/edit_ico.png' %}" alt="Edytuj" width="20" height="20">Edytuj urlop</p>
        {% endif %}
    </div>

</div>

{% endblock body_block %}

holiday_app/templates/holiday/holiday_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head_block %}
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

    {{ form.media }}

{% endblock %}

{% block body_block %}
<div class="container">
    <h1>Edytuj urlop</h1>
    <form method="POST" action="{% url 'holiday_app:holiday_update' pk=holiday.pk %}" class="update-form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-center">
            <input type="submit" value="Uaktualnij" class="btn-action btn btn-primary btn-large">
        </div>
    </form>
</div>
{% endblock %}